//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSIH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mCatalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mCatalogo()
        {
            this.Catalogo1 = new HashSet<Catalogo>();
        }
    
        public int registro_id { get; set; }
        [Required]
        [StringLength(100, MinimumLength = 2)]
        [RegularExpression("^[a-zA-Z0-9 ]*$", ErrorMessage = "SOLO SE PERMITE LETRAS Y NÚMEROS")]
        public string catalogo { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalogo> Catalogo1 { get; set; }
    }
}
