//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSIH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mCita()
        {
            this.mTratamiento = new HashSet<mTratamiento>();
        }
    
        public int registro_id { get; set; }
        public int paciente_id { get; set; }
        public int medico_id { get; set; }
        public int especialidad_id { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime hora { get; set; }
        public string motivo { get; set; }
        public bool estado { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual mAtencion mAtencion { get; set; }
        public virtual mPersona mPersona { get; set; }
        public virtual mPersona mPersona1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mTratamiento> mTratamiento { get; set; }
    }
}
