//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSIH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mCita
    {
        public int registro_id { get; set; }
        public int paciente_id { get; set; }
        public int medico_id { get; set; }
        public int especialidad_id { get; set; }
        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Cita")]
        public System.DateTime fecha { get; set; }
        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh:mm}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hora de Cita")]
        public System.DateTime hora { get; set; }
        public string motivo { get; set; }
        public bool estado { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual mAtencion mAtencion { get; set; }
        public virtual mPersona mPersona { get; set; }
        public virtual mPersona mPersona1 { get; set; }
    }
}
