//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSIH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mParametros
    {
        public int registro_id { get; set; }
        public string smtpserver { get; set; }
       
        public int smtppuerto { get; set; }
        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [RegularExpression(@"^\S*$", ErrorMessage = "EL CORREO ELECTÓNICO NO PUEDE TENER ESPACIOS NI CARACTERES ESPECIALES")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string correo_sistema { get; set; }
        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [DataType(DataType.Password)]
        public string clave_correo { get; set; }
        public bool estado { get; set; }
    }
}
