//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSIH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class mPersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mPersona()
        {
            this.mAuditoria = new HashSet<mAuditoria>();
            this.mCita = new HashSet<mCita>();
            this.mCita1 = new HashSet<mCita>();
            this.rMedico_Calendario = new HashSet<rMedico_Calendario>();
            this.rRol_Persona = new HashSet<rRol_Persona>();
            this.rMedico_Especialidad = new HashSet<rMedico_Especialidad>();
        }
    
        public int registro_id { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [Display(Name = "SELECCIONE TIPO DE IDENTIFICACIÓN")]
        [DisplayFormat(NullDisplayText = "TIPO DE IDENTIFICACIÓN NO SELECCIONADO")]
        public int identificacion_tipo { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [StringLength(13, MinimumLength = 10)]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "SOLO SE PERMITEN NÚMEROS")]
        public string identificacion { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [StringLength(100, MinimumLength = 2)]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "SOLO SE PERMITE LETRAS")]
        public string nombres { get; set; }

        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [StringLength(100, MinimumLength = 2)]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "SOLO SE PERMITE LETRAS")]
        public string apellidos { get; set; }


        [Required(ErrorMessage = "{0} ES REQUERIDO")]
        [StringLength(100, MinimumLength = 10)]
        public string direccion { get; set; }


        
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "SOLO SE PERMITEN NÚMEROS")]
        [StringLength(10, MinimumLength = 7)]
        public string telefono { get; set; }


        [RegularExpression("(^[0-9]+$)", ErrorMessage = "SOLO SE PERMITEN NÚMEROS")]
        [StringLength(10, MinimumLength = 10)]
        public string celular { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Nacimiento")]
        public System.DateTime fecha_nacimiento { get; set; }

        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [RegularExpression(@"^\S*$", ErrorMessage = "EL CORREO ELECTÓNICO NO PUEDE TENER ESPACIOS NI CARACTERES ESPECIALES")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string correo_electronico { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        public int genero { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        public int ciudad_residencia { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        public int nacionalidad { get; set; }


        [Required(ErrorMessage = "{0}  ES REQUERIDO")]
        [DataType(DataType.Password)]
        public string clave { get; set; }

        public bool estado { get; set; }

        public virtual Catalogo Catalogo { get; set; }
        public virtual Catalogo Catalogo1 { get; set; }
        public virtual Catalogo Catalogo2 { get; set; }
        public virtual Catalogo Catalogo3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mAuditoria> mAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mCita> mCita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mCita> mCita1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rMedico_Calendario> rMedico_Calendario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rRol_Persona> rRol_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rMedico_Especialidad> rMedico_Especialidad { get; set; }


    }
}
